import java.awt.*;
import java.io.*;
import javax.swing.*;
import java.util.Vector;
import java.util.regex.Pattern;
import java.util.stream.Collectors;
import javax.swing.DefaultListModel;

public class GradesApprovalPage extends javax.swing.JFrame {
    static Point point;
    DefaultListModel jlist1model,jlist2model;
    boolean flag;

    static JFrame parent;
    
    public GradesApprovalPage(Point point, JFrame parent) {
        initComponents();
        this.point = point;
        this.setLocation(point);
        this.parent = parent;

        jlist1model = new DefaultListModel();
        jlist2model = new DefaultListModel();
        flag = true;
        pendingList.setModel(jlist1model);

        if (flag){
            BufferedReader br = null;
            try{
                br = new BufferedReader(new FileReader("grades.txt"));
                int val = Integer.parseInt(br.readLine());

                for(int i=0;i<val;i++) {
                    String ss = br.readLine();
                    jlist1model.addElement(ss);
                }
                pendingList.setModel(jlist1model);
                flag = false;
            }catch(Exception e) {
                System.out.println("br: " + br + "\nException: "+e);
            }finally{
                try{
                    br.close();
                }catch(Exception e){
                    System.out.println("br: " + br + "\nException: "+e);
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        pendingList = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        approvedList = new javax.swing.JList<>();
        toLeft = new javax.swing.JButton();
        toRight = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jScrollPane1.setViewportView(pendingList);

        jScrollPane2.setViewportView(approvedList);

        toLeft.setText(">");
        toLeft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toLeftActionPerformed(evt);
            }
        });

        toRight.setText("<");
        toRight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toRightActionPerformed(evt);
            }
        });

        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(toRight, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(toLeft, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(backButton)
                        .addGap(231, 231, 231)
                        .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(284, 284, 284)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(toLeft)
                        .addGap(27, 27, 27)
                        .addComponent(toRight))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
                            .addComponent(jScrollPane1))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(backButton)
                    .addComponent(saveButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        
    }//GEN-LAST:event_formWindowOpened

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        int val = pendingList.getModel().getSize(); 
        
        PrintWriter writer = null;
        try{
            writer = new PrintWriter("List.txt");
            writer.println(val);
            
            for(int i=0;i<val;i++){
                writer.println(pendingList.getModel().getElementAt(i));
            }
        }catch(Exception e){
                  System.out.println("Exception: "+e);
              }finally{
            writer.close();
        }
    }//GEN-LAST:event_saveButtonActionPerformed

    private void toLeftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toLeftActionPerformed
        String str2 = pendingList.getSelectedValue();
        
        if(pendingList.getSelectedIndex()==-1){
            JOptionPane.showMessageDialog(rootPane, "No Course Selected...", "Oops..", 1);
        }else{
            int value = pendingList.getSelectedIndex();
            jlist2model.addElement(str2.replaceAll("pending", "approved"));
            approvedList.setModel(jlist2model);

            if(jlist1model.getSize()!=0){
                jlist1model.removeElementAt(value);
            }
            pendingList.setModel(jlist1model);
        }
    }//GEN-LAST:event_toLeftActionPerformed

    private void toRightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toRightActionPerformed
        String str2 = approvedList.getSelectedValue();
        
        if(approvedList.getSelectedIndex()==-1){
            JOptionPane.showMessageDialog(rootPane, "No Course Selected...", "Oops..", 1);
        }else{
            int value = approvedList.getSelectedIndex();
            jlist1model.addElement(str2);
            pendingList.setModel(jlist1model);

            if(jlist2model.getSize()!=0){
                jlist2model.removeElementAt(value);
            }
            approvedList.setModel(jlist2model);
        }
    }//GEN-LAST:event_toRightActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        this.dispose();
        parent.setVisible(true);
    }//GEN-LAST:event_backButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GradesApprovalPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GradesApprovalPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GradesApprovalPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GradesApprovalPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
DefaultListModel<String> listmodel;
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GradesApprovalPage(point, parent).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> approvedList;
    private javax.swing.JButton backButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> pendingList;
    private javax.swing.JButton saveButton;
    private javax.swing.JButton toLeft;
    private javax.swing.JButton toRight;
    // End of variables declaration//GEN-END:variables
}
